services:

  ### GITLAB ###
  gitlab:
    container_name: gitlab
    restart: always
    ports:
      - "8080:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    build:
      context: ./requirements/GitLab
      dockerfile: Dockerfile
    env_file:
      - ./requirements/GitLab/.env
    networks:
      - gitlab_network

  ### JENKINS ###
  jenkins:
    container_name: jenkins
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    build:
      context: ./requirements/Jenkins
      dockerfile: Dockerfile
    env_file:
      - ./requirements/Jenkins/.env
    networks:
      - gitlab_network

  ### NEXUS ###
  nexus:
    container_name: nexus
    restart: always
    ports:
      - "8082:8081"
    volumes:
      - nexus_data:/nexus-data
    build:
      context: ./requirements/Nexus
      dockerfile: Dockerfile
    env_file:
      - ./requirements/Nexus/.env
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
  jenkins_home:
  nexus_data:
