# Jenkins Pipeline Configuration
# This file controls how your CI/CD pipeline runs when triggered automatically

# # Integration controls
enableGitlabStatus: true
enableTelegram: true
enableMetrics: false

# You can add branch-specific configurations in the future
# branches:
#   developer:
#     runTests: true
#     enableTelegram: false
#   main:
#     runTests: true
#     runRuffCheck: true
#     runBanditCheck: true
#     enableTelegram: true