[tool.ruff]
# Allow autofix for all enabled rules (when `--fix`) is provided
fix = true

# Ignore certain rules
ignore = ["N999"]

# Same as Black.
line-length = 88

# Target Python version
target-version = "py39"

# Include other directories if needed
include = ["appflask/**/*.py", "tests/**/*.py"]