apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
data:
  launch-flask-app.sh: |
    #!/bin/bash
    set -e
    echo "Updating apt-get..."
    apt-get update
    echo "Installing wget..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y wget
    echo "Downloading the executable..."
    wget -O /usr/local/bin/flask-app.bin http://nexus-service.nexus.svc.cluster.local:8082/repository/my-artifacts/WmcA/flask-app/1-0/flask-app-1-0.bin
    echo "Setting executable permission..."
    chmod +x /usr/local/bin/flask-app.bin
    echo "Launching the executable..."
    exec /usr/local/bin/flask-app.bin
