apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - apt-get update && apt-get install -y wget && which wget && ls -l /usr/bin/wget && chmod +x /usr/bin/wget && /bin/bash -ic "/usr/bin/wget --version"&& \
            /usr/bin/wget -O /usr/local/bin/flask-app.bin http://nexus-service.default.svc.cluster.local:8082/repository/my-artifacts/WmcA/flask-app/1-0/flask-app-1-0.bin &&
            chmod +x /usr/local/bin/flask-app.bin &&
            /usr/local/bin/flask-app.bin
        env:
        - name: AGENT_NAME
          value: "{{ .Values.env.AGENT_NAME }}"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
