apiVersion: v1
kind: Endpoints
metadata:
  name: nexus-service
subsets:
  - addresses:
      - ip: 192.168.1.27  # Replace with the IP of the Nexus container
    ports:
      - port: 8082
        name: http
        protocol: TCP