apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  ports:
    - port: 8082
      targetPort: 8082
  clusterIP: None  # This makes it a headless service

